### ISSUE TITLE
Optional support for AssetExtension for ImageTwigExtension

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/web-twig#18]
Currently the ImageExtension does not have support for `asset` function this should be introduce by optional injecting the AssetExtension of Symfony Twig Bridge.

E.g.:

```yaml
services:
      Sulu\Twig\Extensions\ImageTwigExtension:
          arguments:
               - 'placeholders'
               - '@?twig.extension.assets'
```

```php
public function __construct(
    ?string $placeholderPath = null, 
    ?AssetExtension $assetExtension, 
    ?string $defaultPackageName
) {
     // ...
}

public function getImage($media, $attributes = [], array $sources = [], ?string $packageName = null): string {
     // ...
}
```
