### ISSUE TITLE
Unknown "get_image" function.

### ISSUE THREAD

**Issue by Romaixn** [sulu/web-twig#34]
Hello,

I have installed sulu/web-twig in my website but this error appear : Unknown "get_image" function.

I have created a sulu_twig.yaml file with this inside : 

```
services:
    _defaults:
        autoconfigure: true

    Sulu\Twig\Extensions\ImageExtension: ~
```

Can you help me with this ?
